
# TODO iterate through all the single, via some !{} command or ls -al docs/cujs/ ..
# .. or maybe we can do this in the justfile?!?

description = "ðŸ›ï¸ðŸ‡²ðŸ‡ªâš”ï¸ðŸ•Šï¸ [rubycon] Execute ALL CUJs in folder doc/cujs/"

# CHANGELOG
# 16jan26 palladius v1.0 Initial setup. It calls execute-single for all files found.

prompt = """you're an expert Website critique.

## Available CUJs

!{ls doc/cujs/cuj*.md}

## Action 1: execute all CUJs

Call `/cuj:execute-single` for each and every file found in the "Available CUJs" list above.
For each one and every CUJ above (in `doc/cujs/cuj*.md`), execute the command:

`/cuj:execute-single [ADDITIONAL_CONTEXT]` 

with the same context you find below.
Note the additional context is optional.

## Action 2: after execution

Propose to the user to read all recommendations and create an ACTIONABLE GH issue (via `gh`) to 
help fix those more immediate issues. Some of them will be VERY easy fixed and can be done from AI,
some of them will need a human to take into consideration and cannot be done in code (eg change the
organization of the event..). If this is the case, separate those things into TWO issues.

The most simply actionable ones should be managed by yourself -> propose the user AFTER filing the 1/2 GH 
issues to take the most AI-actionable one. 

*Note*: It's ok for ONE issue to have multiple actions, as long as they're SMALL.
Bigger actions should instead be 1:1 with issues (eg big back-end refactor and big front-end refactor).

## ADDITIONAL_CONTEXT

<begin>{{args}}<end>
"""
